### ISSUE TITLE
App window is translucent

### ISSUE THREAD

**Issue by acdpsn** [DevER-M/yami#7]
Still usable, very hard to see on dark backgrounds.

Running Windows 10, Python 3.12.6

![image](https://github.com/user-attachments/assets/24b68888-0a21-4301-8067-5d95d5646583)

**Comment by DevER-M** [comment]
will try to fix it

**Comment by DevER-M** [comment]
try now i removed the code which says to chage the opacity to that

**Comment by acdpsn** [comment]
it is fixed
